# The config of Travis
#to use ubuntu 14.04

sudo: required
dist: trusty

matrix:
  include:
    - env: GHC_VER=8.2.2 CABAL_VER=2.0 LLVM=3.9 RUN_BUILD=true THREADED=true IS_DOCKER
      addons:
        apt:
          sources:
            - hvr-ghc
            - llvm-toolchain-trusty
          packages:
            - wget
            - curl
            

# using docker
services:
  - docker

# pre-install
before_install:
  - source $TRAVIS_BUILD_DIR/integration/ci.sh/init.sh


# build
script:
  - source $TRAVIS_BUILD_DIR/integration/ci.sh/build.sh
  # - source $TRAVIS_BUILD_DIR/integration/ci.sh/test.sh

# update docker image
after_success:
- source $TRAVIS_BUILD_DIR/integration/ci.sh/succ.sh
