flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- obj805-server/
extra-deps:
- aeson-1.1.0.0
- ansi-terminal-0.6.2.3
- appar-0.1.4
- async-2.1.1
- attoparsec-0.13.1.0
- auto-update-0.1.4
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.3
- blaze-markup-0.7.1.1
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- case-insensitive-1.2.0.7
- cereal-0.5.4.0
- cipher-aes-0.2.11
- clientsession-0.9.1.2
- conduit-1.2.8
- conduit-extra-1.1.15
- cookie-0.4.2.1
- cprng-aes-0.6.1
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.2.0.0
- dlist-0.8.0.2
- easy-file-0.2.1
- entropy-0.3.7
- exceptions-0.8.3
- fast-logger-2.4.7
- hashable-1.2.5.0
- http-date-0.0.6.1
- http-types-0.9.1
- http2-1.6.2
- integer-logarithms-1
- iproute-1.7.1
- lifted-base-0.2.3.8
- memory-0.14.1
- mmorph-1.0.9
- monad-control-1.0.1.0
- monad-logger-0.3.20.1
- monad-loops-0.4.3
- mtl-2.2.1
- mwc-random-0.13.5.0
- network-2.6.3.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.11
- path-pieces-0.2.1
- primitive-0.6.2.0
- psqueues-0.2.2.3
- random-1.1
- resourcet-1.1.9
- safe-0.3.11
- scientific-0.3.4.10
- securemem-0.1.9
- semigroups-0.18.2
- setenv-0.1.1.3
- shakespeare-2.0.12.1
- simple-sendfile-0.2.25
- skein-1.0.9.4
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.17
- stringsearch-0.3.6.6
- tagged-0.8.5
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unordered-containers-0.2.7.2
- uuid-types-1.0.3
- vault-0.3.0.6
- vector-0.12.0.0
- void-0.7.1
- wai-3.2.1.1
- wai-extra-3.0.19.1
- wai-logger-2.3.0
- warp-3.2.9
- word8-0.1.2
- yesod-core-1.4.30
- zlib-0.6.1.2
resolver: ghc-8.0.2
